runtime: nodejs
env: flex
entrypoint: npm start
runtime_config:
  operating_system: ubuntu22
  runtime_version: "18"

automatic_scaling:
  min_instances: 0
  max_num_instances: 1

handlers:
  - url: /.*
    script: auto
    secure: always